### ISSUE TITLE
Uncaught TypeError: Cannot read properties of undefined (reading 'getLoggerPlugin')

### ISSUE THREAD

**Issue by ffxsam** [braintree/braintree-web#628]
### General information

- SDK version: 3.85.3
- Environment: Sandbox 
- Browser and OS: Chrome 100.0.4896.127 (Official Build) (x86_64) on macOS 11.6.4

### Issue description

I'm using the Braintree/PayPal button within a Vue app. The first time I render the button on a checkout page, there are no issues, but if I navigate to another route then returns to checkout, I get several errors:

```
master-actions.ts:240 Uncaught TypeError: Cannot read properties of undefined (reading 'getLoggerPlugin')
    at Object.handle (master-actions.ts:240:23)
    at a.value (holder.ts:18:21)
    at receiver.ts:68:20
handle @ master-actions.ts:240
value @ holder.ts:18
(anonymous) @ receiver.ts:68
13:13:50.835 master-actions.ts:33 Uncaught TypeError: Cannot read properties of undefined (reading 'getCheckoutUtilsPlugin')
    at Object.handle (master-actions.ts:33:23)
    at a.value (holder.ts:18:21)
    at receiver.ts:68:20
handle @ master-actions.ts:33
value @ holder.ts:18
(anonymous) @ receiver.ts:68
postMessage (async)
C @ component-f78dc18….js:16
(anonymous) @ component-f78dc18….js:16
e @ component-f78dc18….js:16
value @ component-f78dc18….js:16
(anonymous) @ component-f78dc18….js:38
u @ component-f78dc18….js:1
(anonymous) @ component-f78dc18….js:1
(anonymous) @ component-f78dc18….js:1
13:13:50.924 master-actions.ts:42 Uncaught TypeError: Cannot read properties of undefined (reading 'getComponentsAndFieldsPlugin')
    at Object.handle (master-actions.ts:42:23)
    at a.value (holder.ts:18:21)
    at receiver.ts:68:20
```

My hunch is that something is being loaded twice, even though I'm cleaning up if the component containing the button is unmounted:

```ts
  beforeDestroy() {
    this.checkoutInstance?.teardown(); // checkoutInstance: braintree.PayPalCheckout
    // eslint-disable-next-line @typescript-eslint/no-empty-function
    this.clientInstance?.teardown(() => {}); // clientInstance: braintree.Client
  },
```

What's causing this issue and how should I resolve it? Below is the button render code:

```ts
await paypal.Buttons!({
  fundingSource: 'paypal',
  style: {
    color: 'blue',
    height: 36,
  },
  createBillingAgreement: () => {
    return this.checkoutInstance!.createPayment({
      // @ts-ignore
      flow: 'vault',
      amount: 25,
      displayName: 'xx',
      billingAgreementDescription: this.description,
    });
  },
  onApprove: async data => {
    const payload = await this.checkoutInstance!.tokenizePayment(
      data as unknown as PayPalCheckoutTokenizationOptions
    );

    this.$emit('approve', payload.nonce);
  },
  // handle unrecoverable errors
  onError: err => {
    this.$reportError(err, { while: 'fetching information from PayPal' });
  },
}).render(container);
```

**Comment by ffxsam** [comment]
Closing - realized this has nothing to do with Braintree.
